### ISSUE TITLE
Build 132 failed

### ISSUE THREAD

**Issue by ElCep** [cormas/Booklet-CORMAS#2]
I don't understand why but build 132 [failed](https://travis-ci.org/cormas/Booklet-CORMAS/builds/487037357) in Travis CI.
```
./pillar export --to="LaTeX" --outputDirectory=build --outputFile=book.pillar book.pillar
/bin/sh: 1: ./pillar: not found
support/makefiles/pdf.mk:26: recipe for target 'build/book.tex.json' failed
make: *** [build/book.tex.json] Error 127
The command "docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar bash -c "make spiralbook"" exited with 2. 
```
Pillar not found !

**Comment by ElCep** [comment]
The problem was linked to the Pillar docker container. They have changed the way to deal with the VM. I have fixed a part of the problem. But now we can't download the pdf anymore ... It needs to be fixed too!!!

**Comment by SergeStinckwich** [comment]
Thank you Etienne 👍

**Comment by ElCep** [comment]
Travis-ci work again with our Cormas book !
